* Dotfiles

Overcomplicated nix configs for my laptop, PC and server.

** Docs

#+BEGIN_SRC
├── home
│   ├── config
│   │   └── [some configs are linked from here,
│   │        because it's easier to edit the without rebuilding]
│   ├── home.nix
│   ├── hosts
│   │   ├── international - laptop
│   │   │   ├── ...
│   │   │   └── flake.lock - separate lock files for different hosts and from system 
│   │   └── interplanetary - PC
│   │       ├── ...
│   │       └── flake.lock
│   ├── modules
│   │   └── [home manager modules and configurations]
│   └── shared
│       └── [everything that's shared between all hosts]
├── nixos
│   ├── hosts
│   │   ├── international - laptop
│   │   │   ├── ...
│   │   │   └── flake.lock - separate lock files for different hosts
│   │   ├── interplanetary - PC
│   │   │   ├── ...
│   │   │   └── flake.nix
│   │   ├── cumserver - server with lots of stuff
│   │   │   ├── ...
│   │   │   └── flake.lock
│   │   └── shared
│   │       └── everything that's shared between all desktop hosts
│   └── modules
│       └── [system modules and configurations]
├── packages
│   └── [packages, can be used both by system config and home manager]
└── scripts
    └── [some helper scripts here]
#+END_SRC

Note: Some configs in the home manager are linked with activation scripts, so you can edit them without rebuilding the whole system. This means that home configurations are not really pure and you won't be able to apply them to remote hosts.

** Install

1. Enable flakes
2. =git clone https://github.com/nix-community/home-manager.git ~/somewhere=
3. Setup secrets mentioned in =home/secrets.nix= and in =nixos/hosts/shared/secrets.nix=
3. =scripts/u= to build current system based on hostname. or =sudo nixos-rebuild switch --flake ./nixos/hosts/whateverhost/#whateverhostname=
4. =hu= to build home manager configs. or =nix run home-manager/master -- switch --flake ./home/hosts/whateverhost/#sleroq= for the first time time.

** How to understand Nix?

- [[https://github.com/hlissner/dotfiles#frequently-asked-questions][Read links at the buttom]]
- [[https://www.youtube.com/watch?v=Eni9PPPPBpg][Listen to this]]
