{
 "title": "Random stuff",
 "tags": [ "apps" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Navidrome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({unit=\"navidrome.service\"} |= `msg=\"Now Playing\" ` [$__auto]))",
     "legendFormat": "Trask played"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({unit=\"navidrome.service\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Sieve posts over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({unit=\"sieve.service\"} |= `Saved new post` [$__auto])",
     "legendFormat": "Posts saved"
    }
   ]
  },
  {
   "title": "SSH bans over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({unit=\"fail2ban.service\"} |= `Ban` [$__auto]))",
     "legendFormat": "IPs banned"
    }
   ]
  }
 ]
}