{
 "title": "Marzban Shared",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Лучший сервер сейчас",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, avg by(instance) (rate(node_network_receive_bytes_total{instance!~\"Moscow|127.0.0.1:9100|mskp|cumserver\\n|swarsaw\"}[1h]))) * 8",
     "legendFormat": "Самый свободный сервер за последний час: {{instance}}"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Poland",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"Poland\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"Poland\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Germany",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"Germany\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"Germany\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Moscow",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"Moscow\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"Moscow\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  }
 ]
}