{
 "title": "Marzban",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job=\"node\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{job=\"$job\", instance=~\"Moscow|Poland\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic (node info)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(marzban_panel_incoming_bandwidth_speed[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(marzban_panel_outgoing_bandwidth_speed[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic (server total)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\", instance=\"Germany\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", instance=\"127.0.0.1:9100\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic $instance",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "User online status",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "marzban_user_online", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Traffic used changes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(marzban_user_used_traffic[$__rate_interval])",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "TB used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "expr": "marzban_user_used_traffic/1024^4",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}