version: "2"

linters:
  default: none
  enable:
    - containedctx
    - cyclop
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - maintidx
    - modernize
    - nestif
    - nilerr
    - nilnesserr
    - staticcheck
    - unused
