id: no-ternary-in-tsx
language: Tsx
message: Ternary expressions are allowed only inside template expression containers.
severity: error
files:
  - develop/**
rule:
  all:
    - kind: ternary_expression
    - not:
        inside:
          kind: jsx_expression
