ruleDirs:
  - ../../.config/ast-grep/rules/common
  - ../../.config/ast-grep/rules/frg
customLanguages:
  svelte:
    libraryPath: ../../.local/lib/tree-sitter-svelte
    extensions: [svelte]
    languageSymbol: tree_sitter_svelte
languageInjections:
  - hostLanguage: svelte
    rule:
      pattern: <script>$CONTENT</script>
    injected: javascript
  - hostLanguage: svelte
    rule:
      pattern: <script lang="ts">$CONTENT</script>
    injected: typescript
