#!/usr/bin/env bash

set -e

mkdir -p "$SAFE_PLACE"

# Mount the encrypted directory
gocryptfs "$HOME/Sync/Obsidian vault" "$SAFE_PLACE"

# Start Obsidian/LogSeq and wait for it to close
# obsidian
# logseq

# Unmount
# fusermount -u "$SAFE_PLACE"
