#!/usr/bin/env bash

set -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

HOSTNAME=$(hostname)

sudo nixos-rebuild switch --flake "$(dirname "$SCRIPTPATH")"/nixos/hosts/"$HOSTNAME"#sleroq-"$HOSTNAME"
