#!/usr/bin/env bash

set -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

HOSTNAME=$(hostname)
NAME=$(echo "$HOSTNAME" | cut -d'-' -f2)

sudo nixos-rebuild switch --flake "$(dirname "$SCRIPTPATH")"/nixos/hosts/"$NAME"#"$HOSTNAME"
