#!/usr/bin/env bash

set -e

# I am using this script to sync
# configuration from this repo with my system

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

sudo rm -rf /etc/nixos.backup/
sudo mv /etc/nixos /etc/nixos.backup
sudo cp -r "$(dirname "$SCRIPTPATH")"/nixos /etc/nixos

sudo nixos-rebuild switch
